### ISSUE TITLE
Keys.dart file is missing

### ISSUE THREAD

**Issue by alholan** [ShadyBoshra2012/flutter_checkout_payment#1]
the file Keys.dart is missing.. please provide the file :
example/lib/main.dart:
line 12> import 'Keys.dart';
**Target of URI doesn't exist: 'Keys.dart'.
line52>       bool isSuccess = await FlutterCheckoutPayment.init(key: "${Keys.TEST_KEY}");
**Undefined name 'Keys'.
Try correcting the name to one that is defined, or defining the mame.

**Comment by ShadyBoshra2012** [comment]
The file `Keys.dart` is just a file for an example to a test key. You can get it from Checkout platform itself.
