### ISSUE TITLE
How to initiate 3DS flow in sandbox environment?

### ISSUE THREAD

**Issue by RanaOsamaAsif** [ShadyBoshra2012/flutter_checkout_payment#17]
Hi, I wanted to know what are the steps to initiate the 3DS flow using the package.

I've tried entering the 3DS test cards as mentioned in the the docs [here](https://www.checkout.com/docs/testing/test-cards#3D_Secure_test_cards)

And clicking on the handle 3DS button which calls your package's internal `handle3DS` opens an Android webview which does not lead to anywhere and the following error is shown

> The webpage at https://sandbox.checkout.com/api2/v2/3ds/acs/687805 could not be loaded because:
> net::ERR_HTTP_RESPONSE_CODE_FAILURE

Any help here would be appreciated!

**Comment by ShadyBoshra2012** [comment]
Is this issue is still facing you ?

**Comment by edwardmp** [comment]
Hey @RanaOsamaAsif 

I'm actually the one that implemented the 3DS handling for this lib. I'm using it myself without an issue, so trying to understand what's happening for you.

The flow normally goes like this

1) Use this lib to get a token
2) Send the token to your backend to create a payment with it
3) If payment response status is pending, and it contains a url/href, use this lib to handle the challenge

E.g. my implementation looks a bit like this:

```dart

final acquiringCardResponse = await apiService.createAcquiringCard(
  CreateAcquiringCardRequest(
    selectedTokenSummary.token,
  ),
);
if (acquiringCardResponse.redirectUrl != null) {
  final token = await _checkoutService.handleThreeDsChallenge(
    acquiringCardResponse.redirectUrl!,
    acquiringCardResponse.successUrl!,
    acquiringCardResponse.failUrl!,
  );

  await apiService.createAcquiringCard3DSSuccess(
    CreateAcquiringCard3DSSuccessRequest(token),
  );
}
```
