### ISSUE TITLE
Missing functions?

### ISSUE THREAD

**Issue by rockz1999** [ShadyBoshra2012/flutter_checkout_payment#2]
there was no pay function to make the actual payment.. Is there something I'm missing or the plugin lacks the functionality?

**Comment by ShadyBoshra2012** [comment]
Hi @rockz1999 ,

The package is help you to generate token that will be used in the payment process, while the payment process itself MUST be on the server side not in Flutter. So this package doesn't make the whole pay process.

**Comment by rockz1999** [comment]
okay Thank You!! That's a great help

**Comment by ShadyBoshra2012** [comment]
You're welcome.
