### ISSUE TITLE
Google Pay tokenization returns "No value for signature"

### ISSUE THREAD

**Issue by Hassanmohsaid** [ShadyBoshra2012/flutter_checkout_payment#20]
I am integrating with Google Pay and the payment succeeds, after that when I try to tokenize the payment using generateGooglePayToken method, it always returns exception: "**No value for signature**" although the tokenJsonPayload string format is correct as shown below (simplified) and contains the signature from google pay response.
```
{
   "type":"google_pay",
   "token_data":{
      "protocolVersion":"ECv1",
      "signature":"MEQCIDg6/kRoR8af1YTSVfkI9UovV2V+jV8YATG2rvL...juAowEl7rvzbPx8g==",
      "signedMessage":"{\"encryptedMessage\":\"32GByKqzr68CsQ2eYUnx1RJMheZAcp5QQ5LZnrrjymztdmeITfeHn4vLF1WhDjG2U9dxFDTrnOdJxjbHsUFsO/r...0+HR4GWH26ipyMgzF/TMrl3RHrYWM+WKAsJnx\",\"ephemeralPublicKey\":\"BH5/P7a009qJClyZm91+l...CIrEwEeL0Tp72/3NpwrEk\\u003d\",\"tag\":\"u2Mcf/ySnRLdM...FSuO4Nax0k8\\u003d\"}"
   }
}
```
Unfortunately, I couldn't debug the native code. How can this be solved?

**Comment by ShadyBoshra2012** [comment]
@edwardmp Can you support?

**Comment by edwardmp** [comment]
@Hassanmohsaid this is an educated guess, but when creating the payment did you set the gateway to `checkoutltd` and did you set up and created a merchant ID in the Google Pay console?

See https://www.checkout.com/docs/payments/add-payment-methods/google-pay#Step_1:_Integrate_with_Google_Pay

**Comment by edwardmp** [comment]
Otherwise I feel the error indicates that maybe your are not passing the payload as JSON to `generateGooglePayToken`?

For me it looks like this:

```
FlutterCheckoutPayment.generateGooglePayToken(
          tokenJsonPayload: paymentData["paymentMethodData"]["tokenizationData"]
              ["token"],
        )
      ```

**Comment by Hassanmohsaid** [comment]
@edwardmp yes, I setup the gateway, checkout key (based on env.) and merchant id from Google Pay console.

I am passing **tokenJsonPayload** as a string to **generateGooglePayToken** like this:
```
"{
   "type":"google_pay",
   "token_data":{
      "protocolVersion":"ECv1",
      "signature":"MEQCIDg6/kRoR8af1YTSVfkI9UovV2V+jV8YATG2rvL...juAowEl7rvzbPx8g==",
      "signedMessage":"{\"encryptedMessage\":\"32GByKqzr68CsQ2eYUnx1RJMheZAcp5QQ5LZnrrjymztdmeITfeHn4vLF1WhDjG2U9dxFDTrnOdJxjbHsUFsO/r...0+HR4GWH26ipyMgzF/TMrl3RHrYWM+WKAsJnx\",\"ephemeralPublicKey\":\"BH5/P7a009qJClyZm91+l...CIrEwEeL0Tp72/3NpwrEk\\u003d\",\"tag\":\"u2Mcf/ySnRLdM...FSuO4Nax0k8\\u003d\"}"
   }
}"
```
As it requires a **string** not a map, is this wrong?

**Comment by ShadyBoshra2012** [comment]
@Hassanmohsaid I hope that @edwardmp could help you.

Thanks @edwardmp ❤️

**Comment by Hassanmohsaid** [comment]
@ShadyBoshra2012 yes, it is solved now.
Thank you both!
