### ISSUE TITLE
Gradle issue while generating release build

### ISSUE THREAD

**Issue by abdulShanti** [ShadyBoshra2012/flutter_checkout_payment#21]
**Im getting error in gradle when im generating release build**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_checkout_payment:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\Rkcare\.gradle\caches\transforms-3\eb4bc0a6d3470116ff7b5238f1c84854\transformed\core-1.8.0\res\values\values.xml:104:5-113:25: AAPT: error: resource android:attr/lStar not found.

**Comment by edwardmp** [comment]
Does changing the compileVersion fix this issue? https://stackoverflow.com/a/69021791/1422070

**Comment by ShadyBoshra2012** [comment]
Closed due to inactivity.
