### ISSUE TITLE
Token request failed when generating Google Pay token

### ISSUE THREAD

**Issue by Hassanmohsaid** [ShadyBoshra2012/flutter_checkout_payment#23]
I am trying to integrate Google Pay and the tokenization is working fine on testing but on production it produces the following error:
```
Token request failed - request_invalid (HttpStatus: 422)
```
I can't find a solution in the docs, can anyone help me with that?

**Comment by abdullahmansss** [comment]
i'm facing same issue in sandbox environment

**Comment by ShadyBoshra2012** [comment]
Thanks @Hassanmohsaid and @abdullahmansss , I will invistigate in this issue by this week

**Comment by Hassanmohsaid** [comment]
@ShadyBoshra2012 yes, it is working on sandbox, the error appears on the live environment. I did the tokenization manually using checkout's HTTP POST request in the [docs](https://www.checkout.com/docs/payments/add-payment-methods/google-pay#Step_2:_Tokenize_the_Google_Pay_payment_data). It will be great if you figure it out as using the package is much easier. Cheers.

**Comment by edwardmp** [comment]
@Hassanmohsaid easiest would be to look at the 422 error response to determine what is wrong.
Can you set a breakpoint (or add logging) on FlutterCheckoutPaymentPlugin line 196 and look at the error response from Checkout?

**Comment by edwardmp** [comment]
Also, are you sure you are passing the correct token to the library method?

Here's how I'm using it:

```dart
Map<String, dynamic> paymentData = jsonDecode(paymentDataJson);
FlutterCheckoutPayment.generateGooglePayToken(
  tokenJsonPayload: paymentData["paymentMethodData"]["tokenizationData"]
      ["token"],
)
```

**Comment by ShadyBoshra2012** [comment]
Closed due to inactivity
