### ISSUE TITLE
Generate Apple Pay token issue 

### ISSUE THREAD

**Issue by FakharAlyas119** [ShadyBoshra2012/flutter_checkout_payment#25]
I am trying to generate the Apple Pay token but the 
` final result = await FlutterCheckoutPayment.generateApplePayToken(
      paymentDataBase64: generateTokenParams.params,
    );`
do not return the complete response 
`CardTokenisationResponse`  there are some properties that are null please check the below s.s
<img width="505" alt="Screenshot 2024-03-22 at 3 21 44 PM" src="https://github.com/ShadyBoshra2012/flutter_checkout_payment/assets/57287287/5d315830-61c2-4af8-b618-42dd6f6688a2">
@ShadyBoshra2012

**Comment by ShadyBoshra2012** [comment]
@edwardmp Can you help here, please, I am always mention you in the same cases like this 🙈 ❤️ 🙏

**Comment by mattique1234** [comment]
Guyz im also facing an issue. Im passing jsonToken["data"] that is coming from apple but whenever i try to pass it it says
<img width="1104" alt="Screenshot 2024-04-01 at 2 16 18 PM" src="https://github.com/ShadyBoshra2012/flutter_checkout_payment/assets/46107106/a51e37c6-ddc7-4081-ac04-ae42751aaad8">

Here is my code snippet:
<img width="533" alt="image" src="https://github.com/ShadyBoshra2012/flutter_checkout_payment/assets/46107106/4a1f28f5-c3ef-48fa-96b7-e0d48d49150a">

Thanks in advance

**Comment by edwardmp** [comment]
@FakharAlyas119 if you are able to create the token but not all data is filled, I would contact Checkout.com as it can't really have any relation with this Flutter SDK (as it doesn't touch any data returned by native SDKs).

**Comment by FakharAlyas119** [comment]
@edwardmp Yes ,i will appreciate if you can help with this matter

**Comment by ShadyBoshra2012** [comment]
Closed due to inactive
