### ISSUE TITLE
Cannot run release build on Android.

### ISSUE THREAD

**Issue by Hassanmohsaid** [ShadyBoshra2012/flutter_checkout_payment#26]
Whenever I try to run release build on Android using this command:
```
flutter run --release
```
It shows me this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_checkout_payment:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:project_path/build/flutter_checkout_payment/intermediates/merged_res/release/values/values.xml:6134: AAPT: error: resource android:attr/lStar not found.

```
To highlight the main error:
```
AAPT: error: resource android:attr/lStar not found.
```

**Comment by Hassanmohsaid** [comment]
@ShadyBoshra2012 nope, did you make any updates to the repo?

**Comment by ShadyBoshra2012** [comment]
Is this issue solved by latest version which is 1.4.1? @Hassanmohsaid

**Comment by Hassanmohsaid** [comment]
@ShadyBoshra2012 I didn't notice the minSdkVersion in the last [PR](https://github.com/ShadyBoshra2012/flutter_checkout_payment/pull/27), raising it to 31 is a big risk and will make me lose many users based on the percentages [here](https://apilevels.com/).

**Comment by ShadyBoshra2012** [comment]
@lucasuracosta can you please give us some insightes why we need to set minSdkVersion to 31?

**Comment by ShadyBoshra2012** [comment]
Can you please @Hassanmohsaid try to make minSdk to 16 in your local and test if everything is working fine?

**Comment by lucasuracosta** [comment]
Hi!! @ShadyBoshra2012 Sorry for the late reply, I changed the minSdk because I misunderstood [android's latest requirements](https://developer.android.com/google/play/requirements/target-sdk) as I confused targetSdk with minSdk.

I made this following change to comply with Android's requirements and it's fully working in our live app:

![image](https://github.com/user-attachments/assets/cf3f0911-d8c1-4d9a-bf63-f143bb462c00)

**Comment by ShadyBoshra2012** [comment]
It's fine @lucasuracosta 😃 , I fixed it now in the main branch and uploaded a new version 1.4.2. Thanks for you help @lucasuracosta .

You can try it now @Hassanmohsaid
