### ISSUE TITLE
app icon isn't recognized

### ISSUE THREAD

**Issue by rockz1999** [ShadyBoshra2012/flutter_checkout_payment#3]
after using the plugin, my app icon vanishes, I've tried tool:replace too, but no use app icon still doesn't appear back unless I remove the plugin

**Comment by ShadyBoshra2012** [comment]
Thanks for your issue. Now flutter_checkout_payment has been upgraded to latest versions of Checkout Frames. And there's no need to use `tool:replace` any more, also your icon will not disappear again.
