### ISSUE TITLE
how to pay with apple pay,google pay,paypal

### ISSUE THREAD

**Issue by EngYasmeenMahmoud** [ShadyBoshra2012/flutter_checkout_payment#7]
need to know how to pay with apple pay,google pay,paypal??

**Comment by ShadyBoshra2012** [comment]
Hello @EngYasmeenMahmoud, your issue is not related to this package. However you may find your need in this [package](https://pub.dev/packages/pay). And if you need further help, you can find me on [Linkedin](https://linkedin.com/in/ShadyBoshra2012).
