### ISSUE TITLE
Error Occurred: Code: 1. Message: The operation couldn’t be completed. (Frames.NetworkError error 0.). Details: null

### ISSUE THREAD

**Issue by JumanDhaher** [ShadyBoshra2012/flutter_checkout_payment#9]
Error Occurred: Code: 1. Message: The operation couldn’t be completed. (Frames.NetworkError error 0.). Details: null

**Comment by ShadyBoshra2012** [comment]
Please provide more information(Flutter doctor, screenshots, codes) to can help you.

**Comment by JumanDhaher** [comment]
when add payment info and what to generate code send to me this message

**Comment by baptistesx** [comment]
I just had the same issue with the example. Just need to change the expiration date for a non expirated date then it will work.
I spent some time to find the solution, the error message could be clearer :s

**Comment by ShadyBoshra2012** [comment]
Thanks for you clearness @baptistesx , hope this helps you @JumanDhaher.
